"""Export a Hermes-loadable ProjectLens plugin bootstrap."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import shutil
from collections.abc import Sequence


@dataclass(frozen=True)
class HermesPluginExportResult:
    plugin_dir: Path
    bootstrap_path: Path
    manifest_path: Path


def export_hermes_plugin(
    *,
    project_lens_root: Path,
    hermes_plugins_dir: Path,
    plugin_name: str = "projectlens",
    overwrite: bool = False,
) -> HermesPluginExportResult:
    """Create a small Hermes plugin directory that imports ProjectLens.

    The exported plugin is a bootstrap shim. It does not copy ProjectLens data,
    databases, evidence stores, or source files into Hermes. Hermes loads the
    shim, the shim adds this ProjectLens checkout's ``src`` directory to
    ``sys.path``, then it delegates to
    ``project_lens.integrations.hermes_plugin.register``.
    """

    project_root = project_lens_root.resolve()
    project_src = project_root / "src"
    if not project_src.is_dir():
        raise FileNotFoundError(f"ProjectLens src directory not found: {project_src}")

    plugins_dir = hermes_plugins_dir.resolve()
    plugin_dir = plugins_dir / plugin_name
    if plugin_dir.exists():
        if not overwrite:
            raise FileExistsError(f"Hermes plugin directory already exists: {plugin_dir}")
        _remove_existing_plugin_dir(plugin_dir=plugin_dir, plugins_dir=plugins_dir)

    plugin_dir.mkdir(parents=True, exist_ok=False)
    manifest_path = plugin_dir / "plugin.yaml"
    bootstrap_path = plugin_dir / "__init__.py"
    manifest_path.write_text(_manifest(plugin_name), encoding="utf-8")
    bootstrap_path.write_text(_bootstrap(project_src), encoding="utf-8")
    return HermesPluginExportResult(
        plugin_dir=plugin_dir,
        bootstrap_path=bootstrap_path,
        manifest_path=manifest_path,
    )


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Export a Hermes-loadable ProjectLens plugin bootstrap.",
    )
    parser.add_argument(
        "--project-lens-root",
        type=Path,
        default=Path.cwd(),
        help="ProjectLens repository root. Defaults to the current working directory.",
    )
    parser.add_argument(
        "--hermes-plugins-dir",
        type=Path,
        required=True,
        help="Hermes plugins directory where the projectlens bootstrap should be written.",
    )
    parser.add_argument(
        "--plugin-name",
        default="projectlens",
        help="Exported Hermes plugin directory/name. Defaults to projectlens.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite an existing plugin directory with the same name.",
    )
    args = parser.parse_args(argv)
    result = export_hermes_plugin(
        project_lens_root=args.project_lens_root,
        hermes_plugins_dir=args.hermes_plugins_dir,
        plugin_name=args.plugin_name,
        overwrite=args.overwrite,
    )
    print(f"Exported ProjectLens Hermes plugin to: {result.plugin_dir}")
    return 0


def _remove_existing_plugin_dir(*, plugin_dir: Path, plugins_dir: Path) -> None:
    resolved_plugin = plugin_dir.resolve()
    resolved_plugins = plugins_dir.resolve()
    if resolved_plugin == resolved_plugins or resolved_plugins not in resolved_plugin.parents:
        raise ValueError(f"Refusing to remove unsafe plugin directory: {resolved_plugin}")
    shutil.rmtree(resolved_plugin)


def _manifest(plugin_name: str) -> str:
    return f"""name: {plugin_name}
version: 0.1.0
description: Thin Hermes slash-command bridge to ProjectLens read-only project agent.
entrypoint: __init__
commands:
  - project
  - project-map
  - project-gaps
  - project-role
"""


def _bootstrap(project_src: Path) -> str:
    src_text = str(project_src).replace('"', '\\"')
    return f'''"""Bootstrap plugin generated by ProjectLens.

Do not put project facts or memory here. This shim only exposes Hermes
slash commands and delegates all project truth to ProjectLens Kernel.
"""

from __future__ import annotations

import sys

_PROJECT_LENS_SRC = r"{src_text}"
if _PROJECT_LENS_SRC not in sys.path:
    sys.path.insert(0, _PROJECT_LENS_SRC)

from project_lens.integrations.hermes_plugin import register as _projectlens_register


def register(ctx):
    """Register ProjectLens commands in Hermes."""

    return _projectlens_register(ctx)
'''


if __name__ == "__main__":
    raise SystemExit(main())
